version: '3.8'

services:
  locust-master:
    build: ./locust
    ports:
      - "8089:8089"
    environment:
      - LOCUST_MODE=master
    command: >
      locust -f locustfile.py --master --host=https://jsonplaceholder.typicode.com

  locust-worker:
    build: ./locust
    environment:
      - LOCUST_MODE=worker
    depends_on:
      - locust-master
    command: >
      locust -f locustfile.py --worker --master-host=locust-master